import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});




// export const metadata = {
//   title: "PDF Converter Online – PDF to Word, Word to PDF, Image to PDF",
//   description:
//     "Free online PDF conversion tools: PDF to Word, Word to PDF, Image to PDF, Merge, Split, Compress PDF. Fast, secure, no registration required.",
// icons: {
//   icon: "/pdficon.svg",
//     shortcut: "/pdficon-64.png", // clarity ke liye
// }


// };



export const metadata = {
  title: "PDFLinx - PDF Tools",
  description: "Convert PDF files easily online.",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },
};



// export const metadata = {
//   title: "PDF Converter Online – PDF to Word, Word to PDF, Image to PDF",
//   description:
//     "Free online PDF conversion tools: PDF to Word, Word to PDF, Image to PDF, Merge, Split, Compress PDF. Fast, secure, no registration required.",
//   icons: {
//     icon: [
//       { url: "/pdficon.svg", type: "image/svg+xml" }, // SVG for modern browsers
//       { url: "/pdficon-32.png", sizes: "32x32", type: "image/png" }, // Standard favicon
//       { url: "/pdficon-64.png", sizes: "64x64", type: "image/png" }, // Higher resolution
//     ],
//     shortcut: "/pdficon-64.png",
//     apple: [
//       { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }, // iOS home screen
//     ],
//     other: [
//       { rel: "icon", url: "/pdficon-192.png", sizes: "192x192", type: "image/png" }, // Android Chrome
//     ],
//   },
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen bg-gray-50`}
      >
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}





















// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export const metadata = {
//   title: "PDF Converter Online – PDF to Word, Word to PDF, Image to PDF",
//   description: "Free online PDF conversion tools: PDF to Word, Word to PDF, Image to PDF, Merge, Split, Compress PDF. Fast, secure, no registration required.",
// };


// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen bg-gray-50`}
//       >
//         <Navbar />
//         {/* Main content area grows to push footer down */}
//         <main className="flex-grow">{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }


















// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import Navbar from "@/components/Navbar";
// // import Footer from "@/components/Footer";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body className={`${geistSans.variable} ${geistMono.variable}`}>
// //         <Navbar />
// //         {children}
// //         <Footer />
// //       </body>
// //     </html>
// //   );
// // }
